projectName: jquery-mutation-summary
projectUrl: https://joelpurra.com/projects/jquery-mutation-summary
projectGithub: https://github.com/joelpurra/jquery-mutation-summary
projectRedirectBaseUrl: https://joelpurra.com/projects/jquery-mutation-summary
projectStackoverflow: https://stackoverflow.com/search?q=jquery-mutation-summary
